version: '3.8'
services:
# construye el contenedor de la base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: TaskDb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: task
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

# construye el contenedor de la aplicaci√≥n
  app:
    build: .
    container_name: taskservice
    environment:
      DATABASE_URL: "mysql+mysqlconnector://root:1234@TaskDb:3306/task"
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app 
    networks:
      - task-network
    command: sh -c "alembic upgrade head && gunicorn --workers 4 --bind 0.0.0.0:8000 app.main:app"

networks:
  task-network:
    driver: bridge

volumes:
  mysql_data: