services:
#base de datos MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongodb-grpc
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shared-net

#servicio gRPC
  project-grpc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskapi-grpc
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - GRPC_PORT=8086
    ports:
      - "8086:8086"
    networks:
      - shared-net

volumes:
  mongo_data:

networks:
  shared-net:
    external: true

# crear la red externa antes de levantar servicios:
# docker network create shared-net

